### PR TITLE
Add event model to docs toctree

### PR DESCRIPTION
**Pull request by jrmlhermitte**
From issue [here](https://github.com/NSLS-II/bluesky/issues/1070#issuecomment-405099668)

### CODE REVIEW

**Comment by danielballan** [comment]
First someone would have to write some event-model docs.... This link is a 404.

**Comment by prjemian** [comment]
Right.  This link: https://github.com/NSLS-II/event-model

**Comment by jrmlhermitte** [comment]
im fine with either, i think docs would make more sense?

**Comment by jrmlhermitte** [comment]
we can push this for now, but i suggest we write some nice docs for the event model, or the schemas in general. what do you think?

**Comment by prjemian** [comment]
Agree

**Comment by danielballan** [comment]
The [Documents page in the bluesky docs](https://nsls-ii.github.io/bluesky/documents.html) covers the same material and is able to provide some context for why/how these layouts are used. It would be sensible to give event-model standalone documentation as well, but I would make it a low priority relative to other concerns.

**Comment by mrakitin** [comment]
Looks good to me as a placeholder. We can update the link once the docs are available.

**Comment by danielballan** [comment]
I disagree. If someone clicks that link, they might get the wrong impression that all the documentation links are just GitHub repo pages. Let's only link things that meet a certain standard of quality.

My [original suggestion in the issue that prompted this PR](https://github.com/NSLS-II/bluesky/issues/1070#issuecomment-405099668) was to add a link to the Documents page in the bluesky docs. I still think that's the way to go because if you want to understand the Event Model you would start there and then look for a link to learn more (i.e. read the technical schemas).

**Comment by mrakitin** [comment]
OK, I reverted the merge via #86.

**Pull request merged**
