### PR TITLE
new ansible setup info

### PR DESCRIPTION
**Pull request by awalter-bnl**
THis is essentialy a copy of the playbooks read-me file found [here](https://github.com/NSLS-II/playbooks/blob/master/README.md).
I have added some extra info on how to connect after VPNing into the campus network.

The idea is that this will be the main collection of such info as per other items listed here.

FYI I can't confirm that these instructions yet work as I am still not able to use ansible because of some permission issues. So someone else should verify these instructions work

### CODE REVIEW

**Comment by danielballan** [comment]
The build failed because this is an "orphaned" document, not linked from anywhere else. I'll cherry-pick this commit and move it into the `deployment_docs` branch with the other new documents, where we can then add a link.

**Comment by danielballan** [comment]
Cherry-picked to https://github.com/NSLS-II/docs/pull/89/commits/a141853241493594c7d3ed73762b389f5624ce58. See two fix-up commits in that PR that make sphinx build run.

**Comment by mrakitin** [comment]
@danielballan, did you mean you pushed it to #89? It wasn't obvious it was a separate PR :)

**Comment by danielballan** [comment]
Yes, sorry for not being clear. Andrew's commit fba3eb7 above was cherry-picked on #89 as  a141853.

**Comment by mrakitin** [comment]
Great, thanks for the clarification/confirmation!

**Pull request closed without merging**
