### PR TITLE
DOC: add links to all NSLS-II GH orgs

### PR DESCRIPTION
**Pull request by mrakitin**
This was discussed a few times in Slack that it would be good to have some public place where we list all GH orgs. Here is an attempt to do so.

### CODE REVIEW

**Review by danielballan — APPROVED** [review]
:100: Wonderful!

Will these automatically render as links in Sphinx? I would guess that you will need to make them proper external links, as in: 

```rst
`NSLS-II-AMX <https://github.com/NSLS-II-AMX>`_
```

**Comment by mrakitin** [comment]
Thanks @danielballan! Yes, sphinx seems to render them just fine (all clickable links when generated locally):
image
I can go through all of them and define as proper links as you suggested.

Also, I went through all the orgs, and added the logos to each of them. The logos were grabbed as a screenshot from pages like https://www.bnl.gov/ps/beamlines/beamline.php?r=2-ID.

NYXXPDXFPXFMTESSSTSRXQASPDFLIXIXSISRIOSHXNFXIFMXMETFISESMCMSBMMAMX

**Comment by stuartcampbell** [comment]
@mrakitin Thank you for doing this, Cara will be sending you the proper images as well so you have them.

**Comment by mrakitin** [comment]
Great, thanks @stuartcampbell. It was a bit annoying to crop the logos :)

**Comment by mrakitin** [comment]
@danielballan, I addressed your comment regarding the links via 3d273f1.

I received the logos from Cara, and updated most of the BL repos where applicable. There is still a discussion about custom logos for a few beamlines.

**Comment by mrakitin** [comment]
I'm hesitant on adding https://github.com/NSLS-II-HEX to the list, as it's still [under development](https://www.bnl.gov/ps/beamlines/). Should we add it in advance? That will mean we will have to create a Basecamp project for that as well to leverage @tacaswell's automation tooling.

**Comment by mrakitin** [comment]
Any objections to merge it?

**Comment by stuartcampbell** [comment]
No objections from me.

**Comment by mrakitin** [comment]
Thank you, @stuartcampbell!

**Pull request merged**
